name: Deploy Javadoc to GitHub Pages (Maven)
on: workflow_dispatch
# on:
#   push:
#     branches: [master]


jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Move built jars
        run: |
          mkdir staging
          cp -r target staging
      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/apidocs
          allow_empty_commit: true
