name: Deploy to GitHub Pages
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "gh-pages"
      update-latest:
        required: false
        type: boolean
        default: false
      versioned-page:
        required: false
        type: boolean
        default: true

jobs:
  docs:
    runs-on: "ubuntu-latest"
    if: ${{ inputs.versioned-page || inputs.update-latest  }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Download Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: ${{ inputs.artifact-name }}
          path: source
      - name: Create staging directory
        run: mkdir staging
      - name: Copy to versioned page
        if: ${{ inputs.versioned-page }}
        run: cp -r source staging/${{ inputs.project-version }}
      - name: Copy to latest
        if: ${{ inputs.update-latest }}
        run: cp -r source staging/latest
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2 # v4.6.3
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
