name: Deploy to GitHub Pages
on:
  workflow_call:
    inputs:
      project-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      target-branch-name:
        required: false
        type: string
        default: "gh-pages"
      update-latest:
        required: false
        type: boolean
        default: false
      versioned-page:
        required: false
        type: boolean
        default: true

jobs:
  docs:
    runs-on: "ubuntu-latest"
    if: ${{ inputs.versioned-page || inputs.update-latest  }}
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Download Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ inputs.artifact-name }}
          path: source
      - name: Create staging directory
        run: mkdir staging
      - name: Copy to versioned page
        if: ${{ inputs.versioned-page }}
        run: cp -r source staging/${{ inputs.project-version }}
      - name: Copy to latest
        if: ${{ inputs.update-latest }}
        run: cp -r source staging/latest
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          branch: ${{ inputs.target-branch-name }}
          folder: staging
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: false
