name: Java CI (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      artifact-directory:
        required: false
        type: string
        default: "build"
      build-arguments:
        required: false
        type: string
        default: "build"
      package-name:
        required: false
        type: string
        default: "Package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3.6.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.2
        with:
          arguments: ${{ inputs.build-arguments }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.0
        continue-on-error: true
        with:
          name: ${{ inputs.package-name }}-Java-${{ inputs.java-version }}
          path: ${{ inputs.artifact-directory }}
