name: Java CI (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      artifact-directory:
        required: false
        type: string
        default: "build"
      build-arguments:
        required: false
        type: string
        default: "build"
      package-name:
        required: false
        type: string
        default: "Package"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      upload-test-results:
        required: false
        type: boolean
        default: false
      test-result-paths:
        required: false
        type: string
        default: "**/build/test-results/test/TEST-*.xml"
      cache-disabled:
        required: false
        type: boolean
        default: false
      caching-refs:
        required: false
        type: string
        default: |
          refs/heads/main
          refs/heads/master
          refs/heads/develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2
        with:
          cache-disabled: ${{ inputs.cache-disabled }}
          cache-read-only: ${{ !contains(inputs.caching-refs, github.ref) }}
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew ${{ inputs.build-arguments }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@ee6b445351cd81e2f73a16a0e52d598aeac2197f # v5.3.0
        if: ${{ inputs.upload-test-results && (success() || failure()) }}
        with:
          report_paths: ${{ inputs.test-result-paths }}
          check_name: JUnit Test Report (Java ${{ inputs.java-version }})
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        continue-on-error: true
        with:
          name: ${{ inputs.package-name }}-Java-${{ inputs.java-version }}
          path: ${{ inputs.artifact-directory }}
