name: Java CI (Gradle)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      artifact-directory:
        required: false
        type: string
        default: "build"
      build-arguments:
        required: false
        type: string
        default: "build"
      package-name:
        required: false
        type: string
        default: "Package"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      upload-test-results:
        required: false
        type: boolean
        default: false
      test-result-paths:
        required: false
        type: string
        default: "**/build/test-results/test/TEST-*.xml"
      cache-disabled:
        required: false
        type: boolean
        default: false
      caching-refs:
        required: false
        type: string
        default: |
          refs/heads/main
          refs/heads/master
          refs/heads/develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1
        with:
          cache-disabled: ${{ inputs.cache-disabled }}
          cache-read-only: ${{ !contains(inputs.caching-refs, github.ref) }}
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew ${{ inputs.build-arguments }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@a427a90771729d8f85b6ab0cdaa1a5929cab985d # v5.0.0
        if: ${{ inputs.upload-test-results && (success() || failure()) }}
        with:
          report_paths: ${{ inputs.test-result-paths }}
          check_name: JUnit Test Report (Java ${{ inputs.java-version }})
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        continue-on-error: true
        with:
          name: ${{ inputs.package-name }}-Java-${{ inputs.java-version }}
          path: ${{ inputs.artifact-directory }}
