name: Java CI (Maven)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      artifact-directory:
        required: false
        type: string
        default: "target"
      build-arguments:
        required: false
        type: string
        default: "package"
      package-name:
        required: false
        type: string
        default: "Package"
      upload-artifacts:
        required: false
        type: boolean
        default: true
      upload-test-results:
        required: false
        type: boolean
        default: false
      test-result-paths:
        required: false
        type: string
        default: "**/target/surefire-reports/TEST-*.xml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B ${{ inputs.build-arguments }} --file pom.xml -Djava.version=${{ inputs.java-version }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@62516aa379bff6370c95fd5894d5a27fb6619d9b # v5.2.0
        if: ${{ inputs.upload-test-results && (success() || failure()) }}
        with:
          report_paths: ${{ inputs.test-result-paths }}
          check_name: JUnit Test Report (Java ${{ inputs.java-version }})
      - name: Upload artifacts
        if: ${{ inputs.upload-artifacts }}
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        continue-on-error: true
        with:
          name: ${{ inputs.package-name }}-Java-${{ inputs.java-version }}
          path: ${{ inputs.artifact-directory }}
