name: Java CI (Maven)
on:
  workflow_call:
    inputs:
      java-version: # see https://github.com/actions/setup-java#supported-version-syntax
        required: true
        type: string
      distribution: # see https://github.com/actions/setup-java#supported-distributions
        required: false
        type: string
        default: "temurin"
      artifact-directory:
        required: false
        type: string
        default: "target"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3.3.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Djava.version=${{ inputs.java-version }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        continue-on-error: true
        with:
          name: Package-Java-${{ inputs.java-version }}
          path: ${{ inputs.artifact-directory }}
